В приложенном файле хранятся обучающий набор для модели линейной регресии
последний столбец файла содернжит значения целевой фкнкции.
1. Прочитайте данные из файла в nympy-массив с помощью функции np.loadtxt('linreg_4.txt')
2. Отделите независимые переменные от целевой переменной
3. адаптируйте написанный на уроке код градиентного спуска для нахождения коэффициентов линейной модели
вида y = h0 + h1*x1 + h2*x2 + h3*x3
4. Найдите коэффициенты h методом градиентного спуска.


In [32]:
from matplotlib import pyplot as plt
import math
import numpy as np
data = np.loadtxt('linreg_4.txt')


In [33]:
data

array([[ 1.2995489 ,  1.39046002,  0.34551026,  6.59921909],
       [ 0.55133973,  0.76100408,  0.61751073,  6.49794507],
       [ 1.36703752,  1.08220897,  1.48202247,  9.85891938],
       [ 0.66075662,  0.53680347,  1.79729948, 11.8677346 ],
       [ 1.36860863,  0.59988975,  1.45333969, 12.53867434],
       [ 0.28368774,  0.74663786,  0.17834055,  3.71226365],
       [ 0.1676704 ,  0.63951162,  0.19793459,  2.7758983 ],
       [ 0.95762449,  0.64134092,  1.44930468, 11.67240193],
       [ 1.14202085,  0.46563185,  1.32799891, 11.62869211],
       [ 1.79892507,  0.64081693,  0.10252574,  6.51132204],
       [ 0.90939904,  0.14701733,  1.17305202, 10.54753932],
       [ 0.26396804,  0.8940012 ,  0.42886885,  4.56975022],
       [ 0.80213424,  1.70847004,  0.19117915,  4.95632954],
       [ 1.07404154,  0.0775781 ,  0.95873388,  9.13098119],
       [ 0.2887978 ,  0.62076949,  0.98057211,  5.58599655],
       [ 1.87130211,  0.89764414,  0.64148006,  9.90419046],
       [ 1.88533575,  1.

In [34]:
# Отделите независимые переменные от целевой переменной
x,y=np.hsplit(data,[3])

In [35]:
x

array([[1.2995489 , 1.39046002, 0.34551026],
       [0.55133973, 0.76100408, 0.61751073],
       [1.36703752, 1.08220897, 1.48202247],
       [0.66075662, 0.53680347, 1.79729948],
       [1.36860863, 0.59988975, 1.45333969],
       [0.28368774, 0.74663786, 0.17834055],
       [0.1676704 , 0.63951162, 0.19793459],
       [0.95762449, 0.64134092, 1.44930468],
       [1.14202085, 0.46563185, 1.32799891],
       [1.79892507, 0.64081693, 0.10252574],
       [0.90939904, 0.14701733, 1.17305202],
       [0.26396804, 0.8940012 , 0.42886885],
       [0.80213424, 1.70847004, 0.19117915],
       [1.07404154, 0.0775781 , 0.95873388],
       [0.2887978 , 0.62076949, 0.98057211],
       [1.87130211, 0.89764414, 0.64148006],
       [1.88533575, 1.07126691, 0.84276499],
       [0.61320633, 1.97711409, 0.5294924 ],
       [0.37442475, 0.95855511, 0.60952   ],
       [1.90218982, 0.40603965, 1.03288188],
       [0.70914797, 0.34531127, 0.31365964],
       [0.72542155, 1.13864541, 0.69154681],
       [1.

In [36]:
x.shape

(100, 3)

In [37]:
y

array([[ 6.59921909],
       [ 6.49794507],
       [ 9.85891938],
       [11.8677346 ],
       [12.53867434],
       [ 3.71226365],
       [ 2.7758983 ],
       [11.67240193],
       [11.62869211],
       [ 6.51132204],
       [10.54753932],
       [ 4.56975022],
       [ 4.95632954],
       [ 9.13098119],
       [ 5.58599655],
       [ 9.90419046],
       [ 9.99334692],
       [ 4.21243406],
       [ 5.00662058],
       [12.23517436],
       [ 5.5657149 ],
       [ 6.91802888],
       [ 8.08739893],
       [ 4.64648455],
       [ 5.09666668],
       [ 8.39276296],
       [ 7.10791744],
       [ 5.81065217],
       [ 6.819838  ],
       [ 8.29931442],
       [ 8.61942638],
       [ 9.83004162],
       [10.22453454],
       [ 5.07050944],
       [ 5.67053739],
       [ 9.76487048],
       [10.22725585],
       [ 7.99190628],
       [10.38333587],
       [13.71740949],
       [ 6.65394841],
       [ 3.56505285],
       [11.31303505],
       [ 0.70609735],
       [ 6.70851986],
       [ 5

In [38]:
y.shape

(100, 1)

In [41]:
# адаптируйте написанный на уроке код градиентного спуска для нахождения коэффициентов линейной модели вида
# y = h0 + h1x1 + h2x2 + h3x3
# генерируем данные
# y = h0 + h1x1 + h2x2 + h3x3
# так как у нас  h0, то нам надо единичные столбцы
x_ = np.c_[np.ones((100,1)),x] 

In [42]:
x_

array([[1.        , 1.2995489 , 1.39046002, 0.34551026],
       [1.        , 0.55133973, 0.76100408, 0.61751073],
       [1.        , 1.36703752, 1.08220897, 1.48202247],
       [1.        , 0.66075662, 0.53680347, 1.79729948],
       [1.        , 1.36860863, 0.59988975, 1.45333969],
       [1.        , 0.28368774, 0.74663786, 0.17834055],
       [1.        , 0.1676704 , 0.63951162, 0.19793459],
       [1.        , 0.95762449, 0.64134092, 1.44930468],
       [1.        , 1.14202085, 0.46563185, 1.32799891],
       [1.        , 1.79892507, 0.64081693, 0.10252574],
       [1.        , 0.90939904, 0.14701733, 1.17305202],
       [1.        , 0.26396804, 0.8940012 , 0.42886885],
       [1.        , 0.80213424, 1.70847004, 0.19117915],
       [1.        , 1.07404154, 0.0775781 , 0.95873388],
       [1.        , 0.2887978 , 0.62076949, 0.98057211],
       [1.        , 1.87130211, 0.89764414, 0.64148006],
       [1.        , 1.88533575, 1.07126691, 0.84276499],
       [1.        , 0.61320633,

In [50]:
# lr наш параметр, скорость обучения, на него будем сдвигаться,на каждом шаге считаем градиент и сдвигаемся на какое-то небольшое число
lr = 0.1 # скорость обучения
# lr = 0.001
# iters : количество итераций,сколько раз гоняем наш алгоритм
# iters = 100
iters = 100
# m: количество веторов
m = 100
# h: наш искомый вектор модели,мы его случаным образом заполняем
h = np.random.randn(4,1) # инициализация


In [51]:
 h

array([[ 0.21298442],
       [-0.45943034],
       [-0.0465822 ],
       [ 0.33962061]])

In [52]:
# поиск
for it in range(iters):
# мы считаем градиент по формуле матричной из лекции:
    gradient = (2/m)*x_.T @ (x_ @ h - y)
# находим наш h, hкоторый был отнимаем градиент умноженный на скорость обучения
    h = h - lr * gradient

In [53]:
h

array([[ 2.22851397],
       [ 3.22863049],
       [-1.30625833],
       [ 3.87236285]])

In [54]:
# поиск лучших векторов 
h_best = np.linalg.inv(x_.T.dot(x_)).dot(x_.T).dot(y)

In [55]:
h_best

array([[ 2.25759776],
       [ 3.2189038 ],
       [-1.3177213 ],
       [ 3.86506981]])