In [29]:
class Cat(object):
    def talk(self):
        print('Мяу')

some_cat = Cat()
some_cat.talk()

Мяу


In [30]:
class Cat(object):
    
    def __init__(self, name):
        print('new cat was born')
        self.name = name
 
    def __str__(self):
        res = 'Объект класса Cat \nname:'+ self.name
        return res
#выше функция вернет, что res это объект класса Cat,добавить к строке имя объекта и вывести :
#print(cat1) выведет нам:
#Объект класса Cat 
#name:Bagira
    def talk(self):
        print(self.name,'Мяу')


In [31]:
        
cat1 = Cat('Bagira')

new cat was born


In [32]:
cat1.name

'Bagira'

In [33]:
cat1.talk()

Bagira Мяу


In [34]:
print(cat1)

Объект класса Cat 
name:Bagira


In [39]:
#статические методы

class Cat(object):
    total = 0
#переменная принадлежит имеено классу!
# пишем декоратор,метод будет статический и относится к классу

    @staticmethod
    def count():
        print('total cats:',Cat.total)
    
    def __init__(self, name):
        print('new cat was born')
        self.name = name
        Cat.total +=1
 
    def __str__(self):
        res = 'Объект класса Cat \nname:'+ self.name
        return res
#выше функция вернет, что res это объект класса Cat,добавить к строке имя объекта и вывести :
#print(cat1) выведет нам:
#Объект класса Cat 
#name:Bagira
    def talk(self):
        print(self.name,'Мяу')


In [79]:
Cat.count()

total cats: 2


In [71]:
cat1 = Cat('Bagira')

new cat was born


In [72]:
cat1 = Cat('Viki')

new cat was born


In [73]:
# инкапсуляция

class Cat(object):
    total = 0
#переменная принадлежит имеено классу!
# пишем декоратор,метод будет статический и относится к классу

    @staticmethod
    def count():
        print('total cats:',Cat.total)
    
    def __init__(self, name):
        print('new cat was born')
        self.name = name
        Cat.total +=1
        self.__weight = 300
        
        
    def get_weight(self):
        return self.__weight
    
    def set_weight(self,weight_cat):
        if weight_cat>250:
            self.__weight = weight_cat
        
        
    
    
 
    def __str__(self):
        res = 'Объект класса Cat \nname:'+ self.name
        return res
#выше функция вернет, что res это объект класса Cat,добавить к строке имя объекта и вывести :
#print(cat1) выведет нам:
#Объект класса Cat 
#name:Bagira
    def talk(self):
        print(self.name,'Мяу')


In [74]:
cat= Cat('Тузик')

new cat was born


In [75]:
cat.get_weight()

300

In [76]:
cat.set_weight(500)

In [92]:
# наследование

class Tiger (Cat):

    #определяем констркутор и далее еще вызываем конструктор класса родительского с помощью super()
    def __init__(self, name):
        super().__init__(name)
        self.__stripe_count = 30
        
        
    def __talk(self):
        print('RRRR')


In [93]:
tigra = Tiger('Тигра')

new cat was born


In [94]:
print(tigra)

Объект класса Cat 
name:Тигра


In [95]:
tigra.set_weight(200000)

In [96]:
tigra.get_weight()

200000

In [97]:
tigra.talk()

Тигра Мяу


In [89]:
tigra.stripe_count

30

In [91]:
tigra.talk()

RRRR


In [98]:
import numpy as np


In [99]:
a = np.array([0,2,1])

In [101]:
a, type(a)

(array([0, 2, 1]), numpy.ndarray)

In [103]:
a.dtype, a.dtype.name, a.itemsize

(dtype('int32'), 'int32', 4)

In [105]:
a.ndim

1

In [106]:
a.shape

(3,)

In [107]:
a.size

3

In [108]:
len(a)

3

In [110]:
a= np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [112]:
b = np.ones(5,dtype = np.int64)
b

array([1, 1, 1, 1, 1], dtype=int64)

In [113]:
b = np.zeros_like(a)
b

array([0., 0., 0., 0., 0.])

In [119]:
a = np.arange(0,9,2)
a

array([0, 2, 4, 6, 8])

In [117]:
a = np.linspace(0,8,5)
a

array([0., 2., 4., 6., 8.])

In [118]:
b = np.logspace(0,1,5)
b

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [120]:
a.sum(), a.prod(),a.max(), a.min(),a.mean(),a.std()
# a.prod() - перемножает элементы
# a.mean() среднее арифметическое
# a.std() - стандартное отклонение

(20, 0, 8, 0, 4.0, 2.8284271247461903)

In [121]:
b[1] = -2.56
b

array([ 1.        , -2.56      ,  3.16227766,  5.62341325, 10.        ])

In [122]:
# по элементное сравнение можем делать, <,>...
b == 1

array([ True, False, False, False, False])

In [ ]:
#примет true , если хоть одно значение есть true
np.any(b)

In [ ]:
#все элементы должны быть true
np.all(b)

In [123]:
r = np.array([0.0,0.0,1.0,-1.0])/np.array([1.0,0.0,0.0,0.0])
#ошибки при делении на ноль не будет

C:\Users\laptop\AppData\Local\Temp/ipykernel_15056/2405814306.py:1: RuntimeWarning: divide by zero encountered in true_divide
  r = np.array([0.0,0.0,1.0,-1.0])/np.array([1.0,0.0,0.0,0.0])
C:\Users\laptop\AppData\Local\Temp/ipykernel_15056/2405814306.py:1: RuntimeWarning: invalid value encountered in true_divide
  r = np.array([0.0,0.0,1.0,-1.0])/np.array([1.0,0.0,0.0,0.0])


In [124]:
r

array([  0.,  nan,  inf, -inf])

In [125]:
r[1]

nan

In [127]:
np.isnan(r[1])

True

In [128]:
for i in range(len(a)):
    print(a[i])

0
2
4
6
8


In [132]:
a,b

(array([ 0.        ,  2.        ,  4.        ,  6.        ,  8.        ,
         1.        , -2.56      ,  3.16227766,  5.62341325, 10.        ]),
 array([ 1.        , -2.56      ,  3.16227766,  5.62341325, 10.        ]))

In [130]:
a = np.hstack((a,b))
a

array([ 0.        ,  2.        ,  4.        ,  6.        ,  8.        ,
        1.        , -2.56      ,  3.16227766,  5.62341325, 10.        ])

In [133]:
c = a.copy()
c

array([ 0.        ,  2.        ,  4.        ,  6.        ,  8.        ,
        1.        , -2.56      ,  3.16227766,  5.62341325, 10.        ])

In [134]:
np.hsplit(a,[3,6])

[array([0., 2., 4.]),
 array([6., 8., 1.]),
 array([-2.56      ,  3.16227766,  5.62341325, 10.        ])]

In [135]:
a = np.delete(a,[1,5])
a

array([ 0.        ,  4.        ,  6.        ,  8.        , -2.56      ,
        3.16227766,  5.62341325, 10.        ])

In [136]:
len(a)

8

In [137]:
a = np.insert(a,3, [0.,1.])

In [138]:
a

array([ 0.        ,  4.        ,  6.        ,  0.        ,  1.        ,
        8.        , -2.56      ,  3.16227766,  5.62341325, 10.        ])

In [139]:
a[::2]

array([ 0.        ,  6.        ,  1.        , -2.56      ,  5.62341325])

In [140]:
a[::2] = 3
a

array([ 3.        ,  4.        ,  3.        ,  0.        ,  3.        ,
        8.        ,  3.        ,  3.16227766,  3.        , 10.        ])

In [141]:
c = np.ones(5)
c[2] = 56
c

array([ 1.,  1., 56.,  1.,  1.])

In [143]:
a[::2] = c
a

array([ 1.        ,  4.        ,  1.        ,  0.        , 56.        ,
        8.        ,  1.        ,  3.16227766,  1.        , 10.        ])

In [150]:
b = a[1:5].copy()
b

array([ 2.,  1.,  0., 56.])

In [151]:
b[0]=3

In [152]:
b

array([ 3.,  1.,  0., 56.])

In [153]:
a = np.array([[1,0],[0,-1]])

In [154]:
a.size

4

In [155]:
len(a)

2

In [157]:
a.shape

(2, 2)

In [158]:
a.ndim

2