1.Дополните разработанный на уроке класс Cat атрибутом сытости кошки, который может принимать значения от 1 до 5.
Кроме того дополните класс двумя методами:

1.1. "покормить кошку", в результате работы которого уровень сытости кошки повышается на 1, а вес увеличивается на 30 гр.

1.2. "поиграть с кошкой", в результате работы которого уровень сытости кошки снижается на 1, а вес уменбшается на 10 гр.

Исходный класс приведен ниже

In [1]:
class Cat():
    
    total = 0
    
    @staticmethod
    def count ():
        print ('Всего кошек ', Cat.total)
    
    def __init__(self, name):
        print ('Родилась новая кошка')
        self.name = name
        Cat.total += 1
        self.__w = 300 
        self.fullness = 1
    
    def get_weight (self):
        return self.__w

    
    def set_weight (self, we):
        if we > 250:
            self.__w = we
            
 #......           
    def feed (self) :
        if (self.fullness +1) > 5:
            print('Кошка и так сыта')
        else :
            self.fullness +=1
            self.set_weight(self.__w +30)
            print("Кошка покормлена и поправилась на 30 грамм")
 #.......
    def play(self):
        if (self.fullness - 1) < 1:
            print('Кошка голодная, покормите ее')
        else :
            self.fullness -=1
            self.set_weight(self.__w -10)
            print('Кошка поиграла,похудела на 10 грамм')
        
    
    def __str__(self):
        res = 'Объект класса Cat \nname: '+self.name
        return res
    
    def talk(self):
        print (self.name, 'Мяу')

2. Напишите интерактивную программу, которая по вводу числа (буквы) с клавиатуры позволит (): 
2.1. Поговорить с кошкой (вызвать метод talk())
2.2. Покормить кошку
2.3. Поиграть с кошкой
2.4. Взвесить кошку (вызвать метод get_weight())
2.5. завершить работу

In [2]:
def Menu(CatGame):
    
    answer = True
    while answer:
        print('1.Поговорить с кошкой\n 2.Покормить кошку\n 3.Поиграть с кошкой\n 4.Взвесить кошку\n 5.завершить работу')
          
        answer = input("Что вы выберете?")
        if answer == '1.':
            CatGame.talk()
        elif answer == '2.':
            CatGame.feed()
        elif answer == '3.':
            CatGame.play()
        elif answer == '4.':
            CatGame.get_weight()
        elif answer == '5.':
            print("Вы завершили игру! Можете вернуться в начало")

In [3]:
# Мы создаем кота вначале и передаем его в нашу меню функцию 
CatGame = Cat("Kesha")

Родилась новая кошка


In [4]:
# после того,как мы создали кота,мы его передаем в меню наше
Menu(CatGame)

1.Поговорить с кошкой
 2.Покормить кошку
 3.Поиграть с кошкой
 4.Взвесить кошку
 5.завершить работу
Что вы выберете?1
1.Поговорить с кошкой
 2.Покормить кошку
 3.Поиграть с кошкой
 4.Взвесить кошку
 5.завершить работу


KeyboardInterrupt: Interrupted by user

3. Создайте 2 массива одинаковой длинны (20 элементов)
первый массив с помошью функции arrange, второй массив с помошью функции linspace (параметры на ваше усмотрение)
1. Найдите поэлементные произведение, сумму и разность этих массивов.
2. Умножте первый массив на 20
3. на четные позиции второго массива поставьте 0
4. Сравните массивы поэлементно.


In [43]:
# Создайте 2 массива одинаковой длинны (20 элементов) первый массив с помошью функции arrange,
#второй массив с помошью функции linspace (параметры на ваше усмотрение)
import numpy as np

A =np.arange(2,42,2)
B = np.linspace(1,50,20)

In [44]:
A

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [45]:
len(A)

20

In [46]:
B

array([ 1.        ,  3.57894737,  6.15789474,  8.73684211, 11.31578947,
       13.89473684, 16.47368421, 19.05263158, 21.63157895, 24.21052632,
       26.78947368, 29.36842105, 31.94736842, 34.52631579, 37.10526316,
       39.68421053, 42.26315789, 44.84210526, 47.42105263, 50.        ])

In [47]:
len(B)

20

In [49]:
#Найдите поэлементные произведение, сумму и разность этих массивов.

Sum = A + B
Dif = A - B
Prod = A * B


In [50]:
Sum 

array([ 3.        ,  7.57894737, 12.15789474, 16.73684211, 21.31578947,
       25.89473684, 30.47368421, 35.05263158, 39.63157895, 44.21052632,
       48.78947368, 53.36842105, 57.94736842, 62.52631579, 67.10526316,
       71.68421053, 76.26315789, 80.84210526, 85.42105263, 90.        ])

In [51]:
Dif

array([  1.        ,   0.42105263,  -0.15789474,  -0.73684211,
        -1.31578947,  -1.89473684,  -2.47368421,  -3.05263158,
        -3.63157895,  -4.21052632,  -4.78947368,  -5.36842105,
        -5.94736842,  -6.52631579,  -7.10526316,  -7.68421053,
        -8.26315789,  -8.84210526,  -9.42105263, -10.        ])

In [52]:
Prod

array([   2.        ,   14.31578947,   36.94736842,   69.89473684,
        113.15789474,  166.73684211,  230.63157895,  304.84210526,
        389.36842105,  484.21052632,  589.36842105,  704.84210526,
        830.63157895,  966.73684211, 1113.15789474, 1269.89473684,
       1436.94736842, 1614.31578947, 1802.        , 2000.        ])

In [53]:
# Умножте первый массив на 20
A1 = A.copy()
A1 = A1 * 20
A1

array([ 40,  80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480, 520,
       560, 600, 640, 680, 720, 760, 800])

In [63]:
# на четные позиции второго массива поставьте 0
for i in range(len(B)):
    if i%2 == 1:
        B[i] = 0
      

In [64]:
B

[]

In [56]:
# Сравните массивы поэлементно A).
A
B
A,B = [],[]

for i, x in enumerate(A):
    for j, y in enumerate (B):
        if x == y:
            A.append(i)
            B.append(j)
            
print(A)
print(B)

[]
[]


In [57]:
# Сравните массивы поэлементно B).

for i in range(0,len(B)):
    if B[i]==A[i]:
        print(c.append(int(B[i])))

In [58]:
# Сравните массивы поэлементно C).
# intersect1d() function find the intersection of two arrays and return the sorted, 
#unique values that are in both of the input arrays.
A
B
print(np.intersect1d(A,B))

[]
