In [1]:
import numpy as np

# 1. Напиши функцию, которая принимает матрицу и вектор, далее прибавляет вектор к каждой строке матрицы и возвращает результат.
Обязательно проверь размерности.

In [13]:
def add_vector (x,y):
    
# проверяем размерность assert len(x.shape) 
    assert len(x.shape) == 2,'axis not 2'
#если размер (количество) столбцов массива (x) не равен размеру (количеству) столбцов вектора (y),тогда 'dif shapes, try again'
    if x.shape[1] != y.shape[1]:
        return 'dif shapes, try again'
    
    x = x.copy()
# проходимся по всем значениям строк x.shape[0] и всем значениям столбцов x.shape[1] и суммируем массив и вектор
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            return x + y

In [22]:
add_vector(matrix,vector)

array([[ 21,  42,  63],
       [ 54,  75,  96],
       [ 87, 108, 129],
       [ 15,  26,  37]])

In [20]:
vector = np.array([[10, 20, 30]])
matrix = np.array([[11, 22, 33],
                   [44, 55, 66],
                   [77, 88, 99],
                    [5,6,7]])


In [3]:
vector.shape[1]

3

In [21]:
matrix.shape[1]

3

# 2. Напиши функцию алгебраического умножения матриц.
# Напомню матрицы умножаются строка нa столбец.

произведения A·B и B·A можно определить только в том случае, когда число столбцов A совпадает с числом строк B, а число строк A совпадает с числом столбцов B. При этом обе матрицы A·B и B·A будут квадратными, но порядки их будут разными.

# вариант 1

In [29]:
def matrix_multiplication(x,y):
    
# проверяем размерность assert len(x.shape) 
    assert len(x.shape) == 2,'axis not 2'
#если число столбцов массива (x) не равен числу строк массива (y),тогда 'dif shapes, try again'
    if x.shape[1] != y.shape[0]:
        return 'still dif shapes, try again'
#если число строк массива (x) не равен числу столбцов массива (y),тогда 'dif shapes, try again'      
    if x.shape[0] != y.shape[1]:
        return 'still dif shapes, try again'
    return x @ y

In [25]:
matrix_multiplication(A,B)

array([[ 2585,  4092,  4785],
       [ 6452, 11418, 13794],
       [ 1925,  7062,  8943]])

In [33]:
A = np.array([[11, 22, 30],
                   [80, 70, 66],
                   [77, 88, 6]])
B = np.array([[11, 22, 33],
                   [7, 55, 66],
                   [77, 88, 99]])


In [18]:
A.shape

(3, 3)

In [19]:
B.shape

(3, 3)

# вариант 2

In [37]:
def matrix_multiplication_2(x,y):
    assert len(x.shape) == 2,'axis not 2'
#если число столбцов массива (x) не равен числу строк массива (y),тогда 'dif shapes, try again'
    if x.shape[1] != y.shape[0]:
        return 'still dif shapes, try again'
#если число строк массива (x) не равен числу столбцов массива (y),тогда 'dif shapes, try again'     
        return 'still dif shapes, try again'
    return np.dot(x,y)

In [38]:
matrix_multiplication_2(A,B)

array([[ 2585,  4092,  4785],
       [ 6452, 11418, 13794],
       [ 1925,  7062,  8943]])

# вариант 3

In [70]:
def matrix_multiplication_3(x,y):
    assert len(x.shape) == 2,'axis not 2'
#если число столбцов массива (x) не равен числу строк массива (y),тогда 'dif shapes, try again'
    if x.shape[1] != y.shape[0]:
        return 'still dif shapes, try again'
#если число строк массива (x) не равен числу столбцов массива (y),тогда 'dif shapes, try again'     
        return 'still dif shapes, try again'
    res = [[0 for x in range(3)] for y in range(3)]
# explicit for loops
    for i in range(len(x)):
        for j in range(len(y[0])):
            for k in range(len(y)):
                res[i][j] += x[i][k] * y[k][j]
 
    print (res)

In [71]:
matrix_multiplication_3(x,y)

[[2585, 4092, 4785], [6452, 11418, 13794], [1925, 7062, 8943]]


In [57]:
x = np.array([[11, 22, 30],
                   [80, 70, 66],
                   [77, 88, 6]])

In [51]:
for i in range(len(x)):
    print (len(x))

3
3
3


In [58]:
y = np.array([[11, 22, 33],
                   [7, 55, 66],
                   [77, 88, 99]])


In [47]:
for j in range(len(y[0])):
    print (y[0])

[11 22 33]
[11 22 33]
[11 22 33]


In [50]:
 print (len(y[0]))

3


In [53]:
res = [[0 for x in range(3)] for y in range(3)]

In [54]:
res

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]