In [1]:
import numpy as np
# у нас есть векторы и мы должны решить :
#1)*(a+b)
#2)a*c + b*(4*c)
# во втором примере мы умножаем скалярно, поэтому нам в ответе надо получить число !!! 

In [4]:
#создаем массивы:

a = np.array((55,-10,14,458,33,-21,5))
b = np.array((89,15,9,45,-22,-8,18))
c = np.array((42,-70,38,1742,176,-68,-16))



In [6]:
#чтобы получить скалярное произведение помимо умножения,также нужно сложение по правилу:a*b = x1*y1+x2*y2..!! important note
(a*b).sum()

25013

In [7]:
a+b

array([144,   5,  23, 503,  11, -29,  23])

In [8]:
2*(a+b)

array([ 288,   10,   46, 1006,   22,  -58,   46])

In [15]:
(a*c).sum() + 4 * (b*c).sum()

1119750

In [16]:
M = np.array([[2,-3],[4,-6]])
N = np.array([[9,-6],[6,-4]])

In [17]:
M

array([[ 2, -3],
       [ 4, -6]])

In [18]:
N

array([[ 9, -6],
       [ 6, -4]])

In [19]:
M*N

array([[18, 18],
       [24, 24]])

In [20]:
M @ N

array([[0, 0],
       [0, 0]])

In [21]:
N @ M

array([[-6,  9],
       [-4,  6]])

In [24]:
B = N @ M

In [25]:
B

array([[-6,  9],
       [-4,  6]])

In [26]:
B.T

array([[-6, -4],
       [ 9,  6]])

In [27]:
det = np.linalg.det(B)

In [28]:
det

0.0

In [35]:
E = np.eye(2)

In [36]:
E

array([[1., 0.],
       [0., 1.]])

In [37]:
B @ E

array([[-6.,  9.],
       [-4.,  6.]])

In [38]:
A = np.array([[1,2,3],[4,89,6],[3,2,64]])
b = np.array([8,9,11])


In [39]:
A

array([[ 1,  2,  3],
       [ 4, 89,  6],
       [ 3,  2, 64]])

In [40]:
b

array([ 8,  9, 11])

In [41]:
A1 = np.linalg.inv(A)

In [42]:
A1

array([[ 1.28278041e+00, -2.75332882e-02, -5.75490860e-02],
       [-5.37124803e-02,  1.24125480e-02,  1.35409614e-03],
       [-5.84518167e-02,  9.02730761e-04,  1.82802979e-02]])

In [45]:
x = A1 @ b

In [46]:
x

array([ 9.38140375, -0.30309185, -0.25840668])

In [47]:
# проверка подходит ли наш ответ 
A @ x

array([ 8.,  9., 11.])