Дана матрица А
       
       [ 9,  2,  2,  5,  1,  5,  7,  6,  8,  7,  1,  4],
       [ 9,  4,  6, 10,  1,  2, 10,  1, 10,  1,  8,  2],
       [ 7,  2,  9,  7,  7,  7, 10,  6,  8,  7,  8,  9],
       [ 1,  3,  2, 10,  7,  1,  2,  1,  6, 10,  7,  1],
       [ 6,  8,  1,  3,  9,  8,  2, 10,  2,  8,  5,  7],
       [ 7,  4,  7,  5,  2,  9,  8,  2,  9, 10,  3,  6],
       [ 6,  2,  1,  5,  7, 10,  4,  1,  3,  7,  5,  9],
       [10,  5,  3,  4,  1,  3,  3,  3,  1,  3,  6,  2],
       [ 5,  5,  4,  1,  4,  8,  5,  2,  9,  2,  9,  2],
       [ 7,  3,  4,  3,  9,  3,  1, 10,  7,  1,  3,  4],
       [ 7,  3,  7,  8,  6,  6,  9,  9,  2,  5,  6,  3],
       [10,  5,  5,  6,  3,  2,  9,  2,  1,  1,  4,  6],
       [ 8,  4, 10,  4, 10,  9,  4,  2,  5,  1,  5,  5],
       [ 4,  9, 10,  1,  9,  3,  8,  4,  7,  9,  5,  6],
       [10,  8,  9,  3, 10, 10,  9,  4,  7,  3,  7,  3],
       [ 6, 10,  6, 10,  1,  1,  4,  5,  2,  6,  5,  2],
       [ 2,  7, 10,  7,  5,  3, 10,  5,  4,  4,  9,  7],
       [ 8, 10,  4,  2,  3,  3,  1,  5,  7,  7,  8, 10]]       
       
1. Определите размер матрицы
2. Определите значений в 10 столбце, 15 строке
3. Определите значение в 12 строке и 9 столбце
Учтите, что строки и столбцы в матрице мы считаем с единицы.

4. Транспонируйте матрицу А
5. Каковы размеры транспонированной матрицы?



In [3]:
import numpy as np

In [4]:
A = np.array([ [ 9,  2,  2,  5,  1,  5,  7,  6,  8,  7,  1,  4],
   [ 9,  4,  6, 10,  1,  2, 10,  1, 10,  1,  8,  2],
   [ 7,  2,  9,  7,  7,  7, 10,  6,  8,  7,  8,  9],
   [ 1,  3,  2, 10,  7,  1,  2,  1,  6, 10,  7,  1],
   [ 6,  8,  1,  3,  9,  8,  2, 10,  2,  8,  5,  7],
   [ 7,  4,  7,  5,  2,  9,  8,  2,  9, 10,  3,  6],
   [ 6,  2,  1,  5,  7, 10,  4,  1,  3,  7,  5,  9],
   [10,  5,  3,  4,  1,  3,  3,  3,  1,  3,  6,  2],
   [ 5,  5,  4,  1,  4,  8,  5,  2,  9,  2,  9,  2],
   [ 7,  3,  4,  3,  9,  3,  1, 10,  7,  1,  3,  4],
   [ 7,  3,  7,  8,  6,  6,  9,  9,  2,  5,  6,  3],
   [10,  5,  5,  6,  3,  2,  9,  2,  1,  1,  4,  6],
   [ 8,  4, 10,  4, 10,  9,  4,  2,  5,  1,  5,  5],
   [ 4,  9, 10,  1,  9,  3,  8,  4,  7,  9,  5,  6],
   [10,  8,  9,  3, 10, 10,  9,  4,  7,  3,  7,  3],
   [ 6, 10,  6, 10,  1,  1,  4,  5,  2,  6,  5,  2],
   [ 2,  7, 10,  7,  5,  3, 10,  5,  4,  4,  9,  7],
   [ 8, 10,  4,  2,  3,  3,  1,  5,  7,  7,  8, 10]])

In [5]:
A

array([[ 9,  2,  2,  5,  1,  5,  7,  6,  8,  7,  1,  4],
       [ 9,  4,  6, 10,  1,  2, 10,  1, 10,  1,  8,  2],
       [ 7,  2,  9,  7,  7,  7, 10,  6,  8,  7,  8,  9],
       [ 1,  3,  2, 10,  7,  1,  2,  1,  6, 10,  7,  1],
       [ 6,  8,  1,  3,  9,  8,  2, 10,  2,  8,  5,  7],
       [ 7,  4,  7,  5,  2,  9,  8,  2,  9, 10,  3,  6],
       [ 6,  2,  1,  5,  7, 10,  4,  1,  3,  7,  5,  9],
       [10,  5,  3,  4,  1,  3,  3,  3,  1,  3,  6,  2],
       [ 5,  5,  4,  1,  4,  8,  5,  2,  9,  2,  9,  2],
       [ 7,  3,  4,  3,  9,  3,  1, 10,  7,  1,  3,  4],
       [ 7,  3,  7,  8,  6,  6,  9,  9,  2,  5,  6,  3],
       [10,  5,  5,  6,  3,  2,  9,  2,  1,  1,  4,  6],
       [ 8,  4, 10,  4, 10,  9,  4,  2,  5,  1,  5,  5],
       [ 4,  9, 10,  1,  9,  3,  8,  4,  7,  9,  5,  6],
       [10,  8,  9,  3, 10, 10,  9,  4,  7,  3,  7,  3],
       [ 6, 10,  6, 10,  1,  1,  4,  5,  2,  6,  5,  2],
       [ 2,  7, 10,  7,  5,  3, 10,  5,  4,  4,  9,  7],
       [ 8, 10,  4,  2,  3,  3,

In [7]:
#1.Определите размер матрицы
size = np.shape(A)
size

(18, 12)

In [17]:
#2.Определите значений в 10 столбце, 15 строке
B= A[14,9]
B

5

In [18]:
#3 Определите значение в 12 строке и 9 столбце Учтите, что строки и столбцы в матрице мы считаем с единицы.
C = A[11,8]

In [19]:
C

1

In [21]:
#4Транспонируйте матрицу А

AT= A.T
AT

array([[ 9,  9,  7,  1,  6,  7,  6, 10,  5,  7,  7, 10,  8,  4, 10,  6,
         2,  8],
       [ 2,  4,  2,  3,  8,  4,  2,  5,  5,  3,  3,  5,  4,  9,  8, 10,
         7, 10],
       [ 2,  6,  9,  2,  1,  7,  1,  3,  4,  4,  7,  5, 10, 10,  9,  6,
        10,  4],
       [ 5, 10,  7, 10,  3,  5,  5,  4,  1,  3,  8,  6,  4,  1,  3, 10,
         7,  2],
       [ 1,  1,  7,  7,  9,  2,  7,  1,  4,  9,  6,  3, 10,  9, 10,  1,
         5,  3],
       [ 5,  2,  7,  1,  8,  9, 10,  3,  8,  3,  6,  2,  9,  3, 10,  1,
         3,  3],
       [ 7, 10, 10,  2,  2,  8,  4,  3,  5,  1,  9,  9,  4,  8,  9,  4,
        10,  1],
       [ 6,  1,  6,  1, 10,  2,  1,  3,  2, 10,  9,  2,  2,  4,  4,  5,
         5,  5],
       [ 8, 10,  8,  6,  2,  9,  3,  1,  9,  7,  2,  1,  5,  7,  7,  2,
         4,  7],
       [ 7,  1,  7, 10,  8, 10,  7,  3,  2,  1,  5,  1,  1,  9,  3,  6,
         4,  7],
       [ 1,  8,  8,  7,  5,  3,  5,  6,  9,  3,  6,  4,  5,  5,  7,  5,
         9,  8],
       [ 4,  2,  9,  

In [22]:
#5 Каковы размеры транспонированной матрицы?
AT.shape

(12, 18)

Возможно ли сложить матрицы А и B если

A

       [[ 5,  7,  4,  3,  9,  1,  3,  7],
       [[ 7,  5,  6, 10, 10,  6,  7,  6]]
    

B

       [[10,  4,  3],
       [ 4,  8,  2],
       [ 4,  6,  4],
       [ 6,  1,  9]]    
        

In [24]:
# Возможно ли сложить матрицы А и B если
# Нет,разные размеры матриц

A = np.array( [[ 5,  7,  4,  3,  9,  1,  3,  7],
   [ 7,  5,  6, 10, 10,  6,  7,  6]])
B = np.array([[10,  4,  3],
   [ 4,  8,  2],
   [ 4,  6,  4],
   [ 6,  1,  9]])                

In [25]:
A

array([[ 5,  7,  4,  3,  9,  1,  3,  7],
       [ 7,  5,  6, 10, 10,  6,  7,  6]])

In [26]:
B

array([[10,  4,  3],
       [ 4,  8,  2],
       [ 4,  6,  4],
       [ 6,  1,  9]])

Умножте матрицу А из предыдущей задачи на 15, а матрицу В на -4

In [28]:
#Умножте матрицу А из предыдущей задачи на 15, а матрицу В на -4
A = np.array( [[ 5,  7,  4,  3,  9,  1,  3,  7],
   [ 7,  5,  6, 10, 10,  6,  7,  6]])
Anew = 15*A
Anew

array([[ 75, 105,  60,  45, 135,  15,  45, 105],
       [105,  75,  90, 150, 150,  90, 105,  90]])

In [29]:
B = np.array([[10,  4,  3],
   [ 4,  8,  2],
   [ 4,  6,  4],
   [ 6,  1,  9]])    

Bnew = -4*B
Bnew

array([[-40, -16, -12],
       [-16, -32,  -8],
       [-16, -24, -16],
       [-24,  -4, -36]])

Даны 2 матрицы

A

      [[ 8,  7,  1],
       [ 7, 10,  6],
       [ 4,  4,  3],
       [ 4, 10,  3]]


B

      [[ 8, 10],
       [ 7,  4],
       [ 3,  3]]
        
Найдете произведение матриц А и В

Существует ли произведение матриц В и А?

In [30]:
A = np.array([[ 8,  7,  1],
   [ 7, 10,  6],
   [ 4,  4,  3],
   [ 4, 10,  3]])

A

array([[ 8,  7,  1],
       [ 7, 10,  6],
       [ 4,  4,  3],
       [ 4, 10,  3]])

In [31]:
B = np.array(  [[ 8, 10],
   [ 7,  4],
   [ 3,  3]])

B

array([[ 8, 10],
       [ 7,  4],
       [ 3,  3]])

In [32]:
#Найдете произведение матриц А и В

A@B

array([[116, 111],
       [144, 128],
       [ 69,  65],
       [111,  89]])

In [34]:
#Существует ли произведение матриц В и А?
#B @ A

Нельзя

Дана матрица B

      [[3, 6, 7, 5],
       [3, 6, 4, 8],
       [1, 3, 8, 8],
       [8, 4, 9, 8]]

Постройте обратную матрицу
Проверьте свое построение

In [35]:
B  = np.array(  [[3, 6, 7, 5],
   [3, 6, 4, 8],
   [1, 3, 8, 8],
   [8, 4, 9, 8]])
B

array([[3, 6, 7, 5],
       [3, 6, 4, 8],
       [1, 3, 8, 8],
       [8, 4, 9, 8]])

In [38]:
B.shape

(4, 4)

In [39]:
det = np.linalg.det(B)

In [40]:
det

1160.9999999999995

In [41]:
#Постройте обратную матрицу Проверьте свое построение

B1 = np.linalg.inv(B)
B1

array([[-0.04823428,  0.01464255, -0.13953488,  0.15503876],
       [ 0.20671835,  0.08010336, -0.11627907, -0.09302326],
       [ 0.13092162, -0.18260121,  0.09302326,  0.00775194],
       [-0.20241171,  0.15073213,  0.09302326,  0.00775194]])

In [42]:
# ДОЛЖНЫ ПОЛУЧИТЬ ЕДИНИЧНУЮ МАТРИЦУ
B@B1

array([[ 1.00000000e+00,  0.00000000e+00, -1.66533454e-16,
         2.08166817e-17],
       [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16,
         1.38777878e-17],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00,
         2.08166817e-17],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00]])

In [43]:
B1@B

array([[ 1.00000000e+00,  1.11022302e-16,  0.00000000e+00,
         0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 2.77555756e-17,  6.24500451e-17,  1.00000000e+00,
         1.38777878e-17],
       [-4.85722573e-17, -1.07552856e-16,  0.00000000e+00,
         1.00000000e+00]])

Решите матричное уравнение Ax=b
Где матрица А

      [[ 7,  3,  1,  3,  8,  2,  9,  1],
       [ 2,  7,  9,  3,  4,  7,  1,  4],
       [10,  6,  6,  9, 10,  5,  9,  7],
       [ 8,  4,  8,  1,  8,  3,  4,  7],
       [ 2,  4,  9,  7,  8,  9, 10,  5],
       [ 8,  5,  1,  5,  3,  6,  9,  3],
       [ 1,  1,  2,  9,  9,  3, 10,  6],
       [ 2, 10,  7,  8,  6,  4,  3,  7]]

Вектор b = [6, 2, 7, 5, 9, 2, 2, 4]

Проверьте свое решение



In [56]:
A = np.array( [[ 7,  3,  1,  3,  8,  2,  9,  1],
   [ 2,  7,  9,  3,  4,  7,  1,  4],
   [10,  6,  6,  9, 10,  5,  9,  7],
   [ 8,  4,  8,  1,  8,  3,  4,  7],
   [ 2,  4,  9,  7,  8,  9, 10,  5],
   [ 8,  5,  1,  5,  3,  6,  9,  3],
   [ 1,  1,  2,  9,  9,  3, 10,  6],
   [ 2, 10,  7,  8,  6,  4,  3,  7]])

b = np.array([6, 2, 7, 5, 9, 2, 2, 4])

In [57]:
A.shape

(8, 8)

In [58]:
# ПРОВЕРЯЕМ определитель, что он не равен нулю
det = np.linalg.det(A)
det

2048719.9999999972

In [59]:
# считаем обратную матрицу
A1 = np.linalg.inv(A)
A1

array([[-0.03225282, -0.02210795,  0.14918144, -0.00719766, -0.00986616,
         0.00482204, -0.07900689, -0.05204225],
       [ 0.10226288, -0.00770628, -0.13255301,  0.00594713, -0.030706  ,
         0.0477586 , -0.02959311,  0.1432309 ],
       [-0.05161369, -0.38466848,  0.12895174,  0.02690656,  0.36124117,
        -0.13405736, -0.32807704,  0.1519583 ],
       [-0.07693243, -0.08254764,  0.24335146, -0.14170506,  0.07233931,
        -0.0855212 , -0.08434876,  0.01379398],
       [ 0.14671844,  0.37577853, -0.03363808, -0.03847768, -0.25890068,
        -0.06794242,  0.2435838 , -0.15831348],
       [-0.00784929,  0.49866795, -0.05882551, -0.05971436, -0.27810975,
         0.1146018 ,  0.28770208, -0.26235894],
       [ 0.01889472, -0.35964407, -0.10744758,  0.07726776,  0.2597866 ,
         0.04351498, -0.16534714,  0.17050646],
       [-0.12670936,  0.04341833, -0.15183334,  0.16259128, -0.12773244,
         0.13629193,  0.18700066, -0.00206958]])

In [61]:
x = A1@b
x

array([ 0.32521477,  0.03292983,  2.8929107 ,  0.73473486, -1.40806455,
       -2.50792592,  1.80472685, -1.43458159])

In [62]:
A@x

array([6., 2., 7., 5., 9., 2., 2., 4.])

Посчитайте определитель матрицы А из предыдущего упражнения