In [2]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
import pipes as pp
from sklearn.svm import SVC   ### замена класса,меняем на другое дальше



# 1.We review the information via transformer. Preparing data for processing format

In [3]:
df = pd.read_csv('train.csv')

df = df.drop(['CustomerID','ID','Name','TypeofLoan','SSN'], axis = 1)

In [4]:
df = pp.myPipe.transform(df)

In [5]:
X = df.drop(['CreditScore','PaymentBehaviour'], axis = 1)

In [6]:
Y = df['CreditScore']

In [7]:
svm_clf = SVC()    ### замена класса

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
sc = StandardScaler()

In [11]:
X = sc.fit_transform(X)
#X_t = sc.transform(X_t)

In [12]:
paramgrid = { 'kernel':['poly','rbf','linear'], 'C':[1,0.5]}   ## замена параметров

In [13]:
GS_cv = GridSearchCV(svm_clf,param_grid = paramgrid, cv = 3)
# cv - количество разбиений

In [ ]:
GS_cv.fit(X,Y)

In [14]:
GS_cv.best_params_

{'max_depth': 13, 'max_features': 15, 'min_samples_split': 11}

In [15]:
best_gs_tree=GS_cv.best_estimator_

In [16]:
best_gs_tree.score(X_t,y_t)

0.9493763473975978

In [17]:
best_gs_tree.score(X,y)

0.9602036495226363

In [18]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_t)
f1_score = (y_t,pred)

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cs = cross_val_score(best_gs_tree,X,y, cv= 5, scoring = 'f1')

In [22]:
cs

array([0.93975768, 0.94165536, 0.94159727, 0.94621953, 0.94366197])

In [24]:
cs.mean()

0.9425783642998244

In [ ]:
# как ускорить процесс с CVM
# ЧТОБЫ НЕ УСНУТЬ НА КРОСС-ВАЛИДАЦИИ И ПОДБОРЕ ПАРАМЕТРОВ
#

# Ускоряем CVM, Cross-validation

# мы разбиваем наши элементы на 10 частей и получаем абсолютно нормальное распределение. и потом можно тренироваться с svn и должно быть намного быстрее, если выборка очень большая

In [7]:
from sklearn.model_selection import StratifiedKFold

In [36]:
kFold = StratifiedKFold(n_splits=10)

In [37]:
iterator = kFold.split(X, y)

In [38]:
type(iterator)

generator

In [39]:
_, subset = next(iterator)

In [ ]:
#если мы нажмем снова _, subset = next(iterator), мы получим наш следующий кусочек данных и снова можем прогонять

In [40]:
subset

array([    0,     1,     2, ..., 10417, 10419, 10421])

In [41]:
subset.shape

(10391,)

In [42]:
X.shape

(103904, 22)

In [43]:
X = X[subset]
y = y[subset]

In [44]:
y.shape

(10391,)

In [45]:
X.shape

(10391, 22)

In [46]:
paramgrid = [{ 'kernel':['rbf'], 'C':[1,0.5]},
          { 'kernel':['poly'], 'degree':[3,4]} ]   ## замена параметров


#в paramgrid можно передавать список из массивов

In [48]:
GS_cv = GridSearchCV(svm_clf,param_grid = paramgrid, cv = 3)
# cv - количество разбиений

In [49]:
GS_cv.fit(X,y)

GridSearchCV(cv=3, estimator=SVC(),
             param_grid=[{'C': [1, 0.5], 'kernel': ['rbf']},
                         {'degree': [3, 4], 'kernel': ['poly']}])

In [50]:
GS_cv.best_params_

{'C': 1, 'kernel': 'rbf'}

In [54]:
best_gs_tree=GS_cv.best_estimator_

In [55]:
best_gs_tree.score(X_t,y_t)

0.9402140437326764

In [56]:
best_gs_tree.score(X,y)

0.9501491675488404

In [57]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_t)
f1_score = (y_t,pred)

# cross validation on new X and y

In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
cs = cross_val_score(best_gs_tree,X,y, cv= 5, scoring = 'f1')

In [60]:
cs

array([0.92917847, 0.9216018 , 0.92359932, 0.93213685, 0.90960135])