In [35]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
import pipes as pp
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
import numpy as np
from sklearn.metrics import confusion_matrix, precision_score, \
              recall_score, f1_score, precision_recall_curve, roc_curve, roc_auc_score, \
              auc, mean_squared_error
from sklearn.metrics import confusion_matrix, precision_score, \
              recall_score, f1_score, precision_recall_curve, roc_curve, roc_auc_score, \
              auc, mean_squared_error, accuracy_score

# 1.We review the information. Preparing data for processing format

In [36]:
df = pd.read_csv('train.csv')

df = df.drop(['CustomerID','ID','Name','TypeofLoan','SSN'], axis = 1)

In [37]:
df = pp.myPipe.transform(df)

In [38]:
df

Month   Age  AnnualIncome  MonthlyInhandSalary  NumBankAccounts  \
0        0.0  23.0      19114.12          1824.843333                3   
1        1.0  23.0      19114.12             0.000000                3   
2        2.0   0.0      19114.12             0.000000                3   
3        3.0  23.0      19114.12             0.000000                3   
4        4.0  23.0      19114.12          1824.843333                3   
...      ...   ...           ...                  ...              ...   
99995    3.0  25.0      39628.99          3359.415833                4   
99996    4.0  25.0      39628.99          3359.415833                4   
99997    5.0  25.0      39628.99          3359.415833                4   
99998    6.0  25.0      39628.99          3359.415833                4   
99999    0.0  25.0      39628.99          3359.415833                4   

       NumCreditCard  InterestRate  NumofLoan  Delayfromduedate  \
0                  4             3        4.0                 3   
1                  4             3        4.0                -1   
2                  4             3        4.0                 3   
3                  4             3        4.0                 5   
4                  4             3        4.0                 6   
...              ...           ...        ...               ...   
99995              6             7        2.0                23   
99996              6             7        2.0                18   
99997              6          5729        2.0                27   
99998              6             7        2.0                20   
99999              6             7        2.0                18   

       NumofDelayedPayment  ...  Occupation_Scientist  Occupation_Teacher  \
0                      7.0  ...                     1                   0   
1                      0.0  ...                     1                   0   
2                      7.0  ...                     1                   0   
3                      4.0  ...                     1                   0   
4                      0.0  ...                     1                   0   
...                    ...  ...                   ...                 ...   
99995                  7.0  ...                     0                   0   
99996                  7.0  ...                     0                   0   
99997                  6.0  ...                     0                   0   
99998                  0.0  ...                     0                   0   
99999                  6.0  ...                     0                   0   

       Occupation_Writer    1    2    3    4    5    6    7  
0                      0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
1                      0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
2                      0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  
3                      0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  
4                      0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
...                  ...  ...  ...  ...  ...  ...  ...  ...  
99995                  0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
99996                  0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
99997                  0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  
99998                  0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  
99999                  0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[100000 rows x 45 columns]

In [39]:
X = df.drop(['CreditScore','PaymentBehaviour'], axis = 1)

In [40]:
Y = df['CreditScore']

In [41]:
X.shape

(100000, 43)

# scaling and standardization of values

In [149]:
#from sklearn.preprocessing import StandardScaler
#mms = StandardScaler()
#X = mms.fit_transform(X)

#from sklearn.preprocessing import MinMaxScaler
#mms = MinMaxScaler()
#X = mms.fit_transform(X)

# Создание проверочного набора (Create a validation set)

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,  Y_test = train_test_split(X, Y, test_size = 0.5, random_state = 0)

In [43]:
X_train.shape, Y_train.shape

((50000, 43), (50000,))

In [44]:
#X_train.shape, Y_train.shape

# a. ML With Teacher

# Дерево решений ( decision tree)

# Version1

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [13]:
tree = DecisionTreeClassifier()   

In [14]:
paramgrid = { 'max_depth' :[5,8,13,17,20], 'min_samples_split':[1,2,4,7,11], 'max_features':[3,4,6,8,15]} 

In [17]:
GS_cv = GridSearchCV(tree,param_grid = paramgrid, cv = 3, scoring = 'f1')
# cv - количество разбиений

In [18]:
GS_cv.fit(X_train,Y_train)

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 903, in fit
    super().fit(
  File "C:\Users\laptop\anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 238, in fit
    raise ValueError("min_samples_split must be an integer "
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\Users\laptop\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. 

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [5, 8, 13, 17, 20],
                         'max_features': [3, 4, 6, 8, 15],
                         'min_samples_split': [1, 2, 4, 7, 11]},
             scoring='f1')

In [19]:
GS_cv.best_params_

{'max_depth': 8, 'max_features': 15, 'min_samples_split': 2}

In [20]:
best_gs_tree=GS_cv.best_estimator_

In [21]:
best_gs_tree.score(X_test,Y_test)

0.82544

In [22]:
best_gs_tree.score(X_train,Y_train)

0.83414

In [24]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_test)
f1_score = (Y_test,pred)

In [25]:
from sklearn.model_selection import cross_val_score

In [26]:
cs = cross_val_score(best_gs_tree,X_train,Y_train, cv= 5, scoring = 'f1')

In [27]:
cs

array([0.68523269, 0.65490798, 0.65228807, 0.67289022, 0.65783836])

In [28]:
cs.mean()

0.6646314628381396

In [153]:
#tree_cl = DecisionTreeClassifier(max_depth=7, min_samples_split=2, min_samples_leaf=1,random_state=0)
#tree_cl.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=7, random_state=0)

In [154]:
#tree_cl.score(X_test,Y_test), tree_cl.score(X_train, Y_train)

(0.7180660849663854, 0.7279303580186366)

# Version2

# Cross - Validation with decision tree

In [29]:
tree_cl = DecisionTreeClassifier(max_depth=7, min_samples_split=2, min_samples_leaf=1,random_state=0)
tree_cl.fit(X_train, Y_train)

DecisionTreeClassifier(max_depth=7, random_state=0)

In [30]:
tree_cl.score(X_test,Y_test), tree_cl.score(X_train, Y_train)

(0.82316, 0.83356)

In [31]:
from sklearn.model_selection import cross_val_score, cross_val_predict

In [32]:
#передаем наш классификатор обученный, и наше множество,на котором учим.cv - то сколько разбиений мы хотим делать
# scoring='roc_auc'
# we pass our trained classifier, and our set on which we learn. cv - how many partitions we want to do
score = cross_val_score(tree_cl, X_train, Y_train, cv=5) 

In [33]:
# получили 5 оценок из множества X, Y
#received 5 ratings from the set X, Y
score

array([0.826 , 0.825 , 0.8224, 0.8237, 0.8285])

In [34]:
score.mean()

0.8251200000000001

In [87]:
from sklearn.tree import export_graphviz

In [95]:
export_graphviz (tree_cl, out_file = 'creditscore_tree.dot', max_depth=7, feature_names=None, class_names=None, label='all', filled=True, leaves_parallel=False, impurity=True, node_ids=False, proportion=False, rotate=False, rounded=True, special_characters=False, precision=3)

# param rounded: When set to True, draw node boxes with rounded corners.
# param filled:  When set to True, paint nodes to indicate majority class for classification,
#                extremity of values for regression, or purity of node for multi-output.

In [96]:
!dot -Tpng creditscore_tree.dot -o creditscore_tree.png

# Отбор случайным лесом (Selection by random forest)

# Version1

In [46]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier() 

In [47]:
paramgrid = { 'n_estimators' :[10,20,30,40,100], 'max_depth':[5,15,19], 'criterion':['gini', 'entropy']}   

In [48]:
GS_cv = GridSearchCV(rf_clf,param_grid = paramgrid, cv = 3,scoring = 'f1')
# cv - количество разбиений

In [49]:
GS_cv.fit(X_train, Y_train)

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 15, 19],
                         'n_estimators': [10, 20, 30, 40, 100]},
             scoring='f1')

In [50]:
GS_cv.best_params_

{'criterion': 'gini', 'max_depth': 19, 'n_estimators': 100}

In [51]:
best_gs_tree=GS_cv.best_estimator_

In [53]:
best_gs_tree.score(X_test,Y_test)

0.85032

In [54]:
best_gs_tree.score(X_train, Y_train)

0.95326

In [55]:
from sklearn.metrics import f1_score
pred = best_gs_tree.predict(X_test)
f1_score = (Y_test,pred)

In [56]:
cs = cross_val_score(best_gs_tree,X_train, Y_train, cv= 5, scoring = 'f1')

In [57]:
cs

array([0.72163444, 0.71298532, 0.71964517, 0.71974991, 0.72586588])

In [58]:
cs.mean()

0.719976144015885

# Version2

In [165]:

randfor_cl = RandomForestClassifier(n_estimators=600, max_depth=5, min_samples_split=2, min_samples_leaf=1, random_state = 0)
randfor_cl.fit(X_train, Y_train)
randfor_cl.feature_importances_


array([4.46953169e-03, 2.63559685e-03, 8.69869281e-03, 4.84615416e-03,
       4.57868013e-02, 5.85697074e-02, 1.43232981e-01, 3.18621702e-02,
       8.63350662e-02, 2.51335648e-02, 3.31470397e-02, 6.50480597e-02,
       1.90523548e-01, 1.94193004e-01, 5.10768653e-04, 6.16939336e-02,
       4.10967956e-03, 1.36748660e-03, 5.91066342e-03, 3.00010927e-02,
       2.30938754e-05, 2.17796443e-05, 3.95808728e-05, 4.34955070e-05,
       5.72739689e-05, 4.87331889e-05, 6.56269208e-05, 3.12278717e-05,
       4.51522555e-05, 2.95096171e-05, 8.79116725e-05, 8.08539492e-05,
       7.99982748e-05, 2.96288536e-05, 5.20203825e-05, 9.46109459e-05,
       1.64982304e-05, 4.83671871e-05, 5.47169403e-04, 1.11580243e-04,
       2.26492770e-05, 3.28124570e-04, 1.95706636e-05])

In [166]:
randfor_cl.score(X_test,Y_test), randfor_cl.score(X_train, Y_train)

(0.6629475992943308, 0.6686692823279385)

# save model

In [ ]:
import pickle
with open('data.pickle', 'wb') as f:
     pickle.dump(data, f)

In [ ]:
with open('data.pickle', 'rb') as f:
     data_new = pickle.load(f)