In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
# выведет матрицу нам 

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')

In [3]:
# СВОЙСТВА

In [4]:
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [5]:
#1. СВОЙСТВО, определитель транспонированной матрицы равен не транспониованной 
round(LA.det(A)),round(LA.det(A.T))

(-14, -14)

In [6]:
#2. если есть столбей или строка,состоящая из нулей,определитель будет равен нулю.
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
B = np.matrix('-4 0 2; 10 0 -1; 8 0 1')


In [7]:
A

matrix([[-4, -1,  2],
        [ 0,  0,  0],
        [ 8,  3,  1]])

In [8]:
B

matrix([[-4,  0,  2],
        [10,  0, -1],
        [ 8,  0,  1]])

In [9]:
round(LA.det(A)), round(LA.det(B))

(0, 0)

In [12]:
#3.При перестановке строк матрицы знак ее определителя меняется на противоположный
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')


In [13]:
round(LA.det(A)), round(LA.det(B))

(-14, 14)

In [ ]:
#4. ЕСЛИ У МАТРИЦЫ ДВЕ ОДИНАКОВЫЕ СТРОКИ,ОПРЕДЕЛИТЕЛЬ РАВЕН НУЛЮ.

In [14]:
A = np.matrix('-4 -1 2; 8 3 1; 8 3 1')

In [15]:
round(LA.det(A))

0

In [17]:
#ЕСЛИ все элементы матрицы умножить на число,то и определитель умножится на это число.

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()

In [18]:
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [19]:
B

matrix([[-4, -1,  2],
        [10,  4, -1],
        [16,  6,  2]])

In [20]:
round(LA.det(A)), round(LA.det(B))

(-14, -28)

In [26]:
# если все элементы строки или столбца можно представить как сумма слагаемых,
#то определитель такой матрицы равен сумме определителя соответст. матриц

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
B = np.matrix('-4 -1 2; 8 5 1; 8 3 1')
C = A.copy()

In [27]:
C[1,:] = A[1,:] + B[1,:]

In [28]:
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [29]:
B

matrix([[-4, -1,  2],
        [ 8,  5,  1],
        [ 8,  3,  1]])

In [30]:
C

matrix([[-4, -1,  2],
        [18,  9,  0],
        [ 8,  3,  1]])

In [31]:
round(LA.det(A)), round(LA.det(B)),round(LA.det(C))

(-14, -40, -54)

In [32]:
# Если к элементам одной строки прибавить элементы другой строки,умноженные на одно и тоже число ,то определительтарицы не изменится

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()


In [33]:
B[1,:] = B[1,:] + k * B[0,:]

In [34]:
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [35]:
B

matrix([[-4, -1,  2],
        [ 2,  2,  3],
        [ 8,  3,  1]])

In [36]:
#8 
#Если строка или столбец матрицы являются линейной комбинацией  других строк(столбцов)б то определитель равен нулю и если
#матрица содержит пропорциональные строки,то определитель равен нулю.
#к это скаляр у нас 

A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2


In [37]:
A

matrix([[-4, -1,  2],
        [10,  4, -1],
        [ 8,  3,  1]])

In [38]:
A[1,:] = A[0,:] + k*A[2,:]

In [76]:
A

array([[1, 2],
       [3, 4]])

In [77]:
round(LA.det(A))

-2

In [78]:
#РАНГ матрицы посчитать

def get_addition (A,i,j):
    A_i = np.delete(A,i,axis = 0)
    A_ij = np.delete(A_i,j,axis = 1)
    return A_ij



In [80]:
A = np.matrix('1 2 0 5; 2 4 -1 0; 4 4 3 2; 1 0 2 1')
A

matrix([[ 1,  2,  0,  5],
        [ 2,  4, -1,  0],
        [ 4,  4,  3,  2],
        [ 1,  0,  2,  1]])

In [81]:
LA.det(A)

0.0

In [84]:
A11 = get_addition (A,0,0)
A11

matrix([[ 4, -1,  0],
        [ 4,  3,  2],
        [ 0,  2,  1]])

In [86]:
LA.det(A11)

0.0

In [51]:
LA.matrix_rank(A)

3

In [63]:
#РЕШАЕМ СИСТЕМУ УРАВНЕНИЙ

A = np.array([[1,2],[1,2]])
b = np.array([[4,-3]])


In [64]:
AA = np.concatenate((A.T,b),axis = 0).T
# функция сцепляет два массива и делаем транспонируемую матрицу(нам надо одна размерность)

In [65]:
AA

array([[ 1,  2,  4],
       [ 1,  2, -3]])

In [66]:
LA.matrix_rank(A), LA.matrix_rank(AA)

(1, 2)

In [67]:
A

array([[1, 2],
       [1, 2]])

In [68]:
b

array([[ 4, -3]])

In [ ]:
# нет решений в системе! ранг должен совпать, если ранки одинаковые,то значит есть решение...
#чтобы проверить надо использовать функцию solve
# LA.solve(A,b)

In [71]:
A = np.array([[1,2],[3,4]])
A1 = np.array([[4,-2],[-3,1]])/(-2)

In [72]:
A@A1

array([[1., 0.],
       [0., 1.]])

In [ ]:
# достанет нам элемент из матрицы (4 строка, 0 столбец,мы начинаем отчет с (0,0!!!))
m = get_addition (B,4,0)

#посмотрим на детерминант этого числа
LA.det(m)



#создадим нулевую матрицу, которую потом будем заполнять элементами
BA = np.zeros((12,12))

for i in range(B.shape[0])