1. Дана матрица В системы уравнений

       [ -8,   6,  -4,   0,   7,   1,   1,  -7,  -3,  -8,   5,  -8],
       [ -4,  -6,   7,  -8,   7,  -7,  -4,   4,   5,   4,  -6,  -4],
       [  0,   1,  -7,  -4,  -6,  -8,   1,   7,   7,   1,  -5,  -1],
       [ -8,   4,  -6,  -8,   0,  -6,   7,  -3,   6,   2,   7,   6],
       [ 12,  -1, -19,   2, -10, -16,  -3,   5,  -7, -13,   5,   9],
       [ -2,  -4,  -4,   0,   4,   0,   1,   0,   4,  -5,  -4,   4],
       [  6,  -1,  -6,   3,  -2,  -4,  -2,  -1,  -7,  -7,   5,   5],
       [  3,   0,  -8,   6,   2,  -4,  -6,  -7,  -2,  -5,  -6,   1],
       [  6,  -3,  -1,  -3,   2,   1,  -5,  -2,   3,  -2,   6,   0],
       [ -8,  -2,   3,  -1,   7,  -1,  -2,   3,  -5,   6,   7,  -1],
       [ -7,  -7,   3,  -2,   5,  -1,  -6,  -6,  -5,   4,   0,  -8],
       [ -1,  -8,  -1,   7,  -6,  -1,   2,  -2,   6,  -7,   3,  -2]
       
и вектор b свободных членов 

       [ 3,  4, -7, -6,  5, -4, -4, -3, -6, -7, -7, -7]

Проверьте совместность системы уравнений с помощью теоремы Кронекера-Капелли

In [ ]:
# rang A = rang(A/B) - Ранг основной матрицы равен рангу расширенной матрицы
# СЛАУ совместна тогда и только тогда, когда ранг её основной матрицы A равен рангу её расширенной матрицы
import numpy as np
from numpy import linalg as LA

In [44]:
B = np.array([[ -8,   6,  -4,   0,   7,   1,   1,  -7,  -3,  -8,   5,  -8],
[ -4,  -6,   7,  -8,   7,  -7,  -4,   4,   5,   4,  -6,  -4],
[  0,   1,  -7,  -4,  -6,  -8,   1,   7,   7,   1,  -5,  -1],
[ -8,   4,  -6,  -8,   0,  -6,   7,  -3,   6,   2,   7,   6],
[ 12,  -1, -19,   2, -10, -16,  -3,   5,  -7, -13,   5,   9],
[ -2,  -4,  -4,   0,   4,   0,   1,   0,   4,  -5,  -4,   4],
[  6,  -1,  -6,   3,  -2,  -4,  -2,  -1,  -7,  -7,   5,   5],
[  3,   0,  -8,   6,   2,  -4,  -6,  -7,  -2,  -5,  -6,   1],
[  6,  -3,  -1,  -3,   2,   1,  -5,  -2,   3,  -2,   6,   0],
[ -8,  -2,   3,  -1,   7,  -1,  -2,   3,  -5,   6,   7,  -1],
[ -7,  -7,   3,  -2,   5,  -1,  -6,  -6,  -5,   4,   0,  -8],
[ -1,  -8,  -1,   7,  -6,  -1,   2,  -2,   6,  -7,   3,  -2]])

In [20]:
B

array([[ -8,   6,  -4,   0,   7,   1,   1,  -7,  -3,  -8,   5,  -8],
       [ -4,  -6,   7,  -8,   7,  -7,  -4,   4,   5,   4,  -6,  -4],
       [  0,   1,  -7,  -4,  -6,  -8,   1,   7,   7,   1,  -5,  -1],
       [ -8,   4,  -6,  -8,   0,  -6,   7,  -3,   6,   2,   7,   6],
       [ 12,  -1, -19,   2, -10, -16,  -3,   5,  -7, -13,   5,   9],
       [ -2,  -4,  -4,   0,   4,   0,   1,   0,   4,  -5,  -4,   4],
       [  6,  -1,  -6,   3,  -2,  -4,  -2,  -1,  -7,  -7,   5,   5],
       [  3,   0,  -8,   6,   2,  -4,  -6,  -7,  -2,  -5,  -6,   1],
       [  6,  -3,  -1,  -3,   2,   1,  -5,  -2,   3,  -2,   6,   0],
       [ -8,  -2,   3,  -1,   7,  -1,  -2,   3,  -5,   6,   7,  -1],
       [ -7,  -7,   3,  -2,   5,  -1,  -6,  -6,  -5,   4,   0,  -8],
       [ -1,  -8,  -1,   7,  -6,  -1,   2,  -2,   6,  -7,   3,  -2]])

In [21]:
b = np.array([[ 3,  4, -7, -6,  5, -4, -4, -3, -6, -7, -7, -7]])

In [22]:
b

array([[ 3,  4, -7, -6,  5, -4, -4, -3, -6, -7, -7, -7]])

In [33]:
#нужно посчитать ранг матрицы:
rank1 = LA.matrix_rank(B)

In [34]:
rank1

11

In [35]:
# функция сцепляет два массива и делаем транспонируемую матрицу(нам надо одна размерность)
BB = np.concatenate((B.T,b),axis = 0).T
BB


array([[ -8,   6,  -4,   0,   7,   1,   1,  -7,  -3,  -8,   5,  -8,   3],
       [ -4,  -6,   7,  -8,   7,  -7,  -4,   4,   5,   4,  -6,  -4,   4],
       [  0,   1,  -7,  -4,  -6,  -8,   1,   7,   7,   1,  -5,  -1,  -7],
       [ -8,   4,  -6,  -8,   0,  -6,   7,  -3,   6,   2,   7,   6,  -6],
       [ 12,  -1, -19,   2, -10, -16,  -3,   5,  -7, -13,   5,   9,   5],
       [ -2,  -4,  -4,   0,   4,   0,   1,   0,   4,  -5,  -4,   4,  -4],
       [  6,  -1,  -6,   3,  -2,  -4,  -2,  -1,  -7,  -7,   5,   5,  -4],
       [  3,   0,  -8,   6,   2,  -4,  -6,  -7,  -2,  -5,  -6,   1,  -3],
       [  6,  -3,  -1,  -3,   2,   1,  -5,  -2,   3,  -2,   6,   0,  -6],
       [ -8,  -2,   3,  -1,   7,  -1,  -2,   3,  -5,   6,   7,  -1,  -7],
       [ -7,  -7,   3,  -2,   5,  -1,  -6,  -6,  -5,   4,   0,  -8,  -7],
       [ -1,  -8,  -1,   7,  -6,  -1,   2,  -2,   6,  -7,   3,  -2,  -7]])

In [36]:
rank2 = LA.matrix_rank(BB)

In [37]:
rank2

12

In [40]:
if rank1 == rank2:
    print('Система совместа и имеет решения:')
elif rank1 != rank2:
    print('система несовместа,нет решений,так как rank1 не равен rank2 неудовлетворяет условию Кронекера-Капелли')

система несовместа,нет решений,так как rank1 не равен rank2 неудовлетворяет условию Кронекера-Капелли


In [ ]:
#РАНГ матрицы посчитать:
def get_addition (A,i,j):
    A_i = np.delete(A,i,axis = 0)
    A_ij = np.delete(A_i,j,axis = 1)
    return A_ij

In [ ]:
# как найти решения сисетмы?..

2. Постройте матрицу алгебраических дополнений для матрицы B из предыдущей задачи

In [ ]:
B = np.array([[ -8,   6,  -4,   0,   7,   1,   1,  -7,  -3,  -8,   5,  -8],
[ -4,  -6,   7,  -8,   7,  -7,  -4,   4,   5,   4,  -6,  -4],
[  0,   1,  -7,  -4,  -6,  -8,   1,   7,   7,   1,  -5,  -1],
[ -8,   4,  -6,  -8,   0,  -6,   7,  -3,   6,   2,   7,   6],
[ 12,  -1, -19,   2, -10, -16,  -3,   5,  -7, -13,   5,   9],
[ -2,  -4,  -4,   0,   4,   0,   1,   0,   4,  -5,  -4,   4],
[  6,  -1,  -6,   3,  -2,  -4,  -2,  -1,  -7,  -7,   5,   5],
[  3,   0,  -8,   6,   2,  -4,  -6,  -7,  -2,  -5,  -6,   1],
[  6,  -3,  -1,  -3,   2,   1,  -5,  -2,   3,  -2,   6,   0],
[ -8,  -2,   3,  -1,   7,  -1,  -2,   3,  -5,   6,   7,  -1],
[ -7,  -7,   3,  -2,   5,  -1,  -6,  -6,  -5,   4,   0,  -8],
[ -1,  -8,  -1,   7,  -6,  -1,   2,  -2,   6,  -7,   3,  -2]])

In [ ]:
B

In [ ]:
def get_addition (B,i,j):
    B_i = np.delete(B,i,axis = 0)
    B_ij = np.delete(B_i,j,axis = 1)
    return A_ij

In [ ]:
# достанет нам элемент из матрицы (4 строка, 0 столбец,мы начинаем отчет с (0,0!!!))
m = get_addition (B,4,0)

In [ ]:
#посмотрим на детерминант этого числа
LA.det(m)


In [ ]:

#создадим нулевую матрицу, которую потом будем заполнять элементами
BA = np.zeros((12,12))
# перебираем строки из матрицы B
for i in range(B.shape[0]):
# бежим по строка и перебираем элементы по столбцам
    for j in range(B.shape[1]):
# достаем наши элементв по очереди
        m.get_addition(B,i,j)
# и ищем для каждого детерминанту
        d = LA.det(m)
# и в конце по формуле матрица алгебраического уравнения равна:
        BA[i,j] = (-1)**(i+j)* round(d)