In [1]:
import os
import tarfile
from six.moves import urllib
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

Загрузка данных с Git и сохранение на в локальный файл

In [2]:
download_path = 'https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.tgz'
housing_path = 'datasets/housing/'

In [3]:
def fetch_housing_data (url = download_path, path_h = housing_path, file_name = 'housing.tgz'):
    
    if not os.path.isdir(path_h):
        os.makedirs(path_h)
        
    tgz_path = os.path.join(path_h, file_name)
    
    urllib.request.urlretrieve (url, tgz_path)
    
    tarf = tarfile.open(tgz_path)
    tarf.extractall(path = path_h)
    tarf.close()    
    

In [4]:
fetch_housing_data()

Подъем файла с данными в память

In [5]:
def load_to_pandas (file_path = housing_path, file_name = 'housing.csv'):
    
    full_path = os.path.join(file_path, file_name)
    
    return pd.read_csv(full_path)

In [6]:
hdf = load_to_pandas()

Осмотр данных 

In [7]:
#hdf.shape

In [8]:
#hdf.head(15)

In [9]:
#hdf.info()

In [10]:
#20640 - 20433

In [11]:
#hdf['ocean_proximity'].value_counts()

Гистограммы

In [12]:
# median_income, median_age, median_value, масштабы и хвосты
#hdf.hist(bins = 50, figsize = (20,15))

In [13]:
#hdf['ocean_proximity'].hist()

Визуализация графических данных

In [14]:
#hdf.plot(kind='scatter', x='longitude', y = 'latitude')

In [15]:
#hdf.plot(kind='scatter', x='longitude', y = 'latitude', alpha = 0.05)

In [16]:
#hdf.plot(kind='scatter', x='longitude', y = 'latitude', alpha = 0.4, label = "population", figsize = (10,7), 
 #            c = 'median_house_value', cmap = 'jet', colorbar = True)

Поиск зависимостей

In [17]:
corr_M = hdf.corr()
corr_M

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924664           -0.108197     0.044568   
latitude            -0.924664  1.000000            0.011173    -0.036100   
housing_median_age  -0.108197  0.011173            1.000000    -0.361262   
total_rooms          0.044568 -0.036100           -0.361262     1.000000   
total_bedrooms       0.069608 -0.066983           -0.320451     0.930380   
population           0.099773 -0.108785           -0.296244     0.857126   
households           0.055310 -0.071035           -0.302916     0.918484   
median_income       -0.015176 -0.079809           -0.119034     0.198050   
median_house_value  -0.045967 -0.144160            0.105623     0.134153   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069608    0.099773    0.055310      -0.015176   
latitude                 -0.066983   -0.108785   -0.071035      -0.079809   
housing_median_age       -0.320451   -0.296244   -0.302916      -0.119034   
total_rooms               0.930380    0.857126    0.918484       0.198050   
total_bedrooms            1.000000    0.877747    0.979728      -0.007723   
population                0.877747    1.000000    0.907222       0.004834   
households                0.979728    0.907222    1.000000       0.013033   
median_income            -0.007723    0.004834    0.013033       1.000000   
median_house_value        0.049686   -0.024650    0.065843       0.688075   

                    median_house_value  
longitude                    -0.045967  
latitude                     -0.144160  
housing_median_age            0.105623  
total_rooms                   0.134153  
total_bedrooms                0.049686  
population                   -0.024650  
households                    0.065843  
median_income                 0.688075  
median_house_value            1.000000

In [19]:
corr_M['median_house_value']

longitude            -0.045967
latitude             -0.144160
housing_median_age    0.105623
total_rooms           0.134153
total_bedrooms        0.049686
population           -0.024650
households            0.065843
median_income         0.688075
median_house_value    1.000000
Name: median_house_value, dtype: float64

Графическая матрица зависимостей

In [61]:
#from pandas.plotting import scatter_matrix

In [262]:
#attributes = ['median_house_value', 'median_income', 'housing_median_age', 'total_rooms']

In [16]:
#scatter_matrix(hdf[attributes], figsize = (12,8))

In [17]:
#hdf.plot(kind='scatter', x='median_income', y = 'median_house_value', figsize = (12,8))

In [18]:
#hdf

Новые атрибуты


In [20]:
hdf['rooms_per_house'] = hdf['total_rooms'] / hdf['households']
hdf['bebrooms_per_room'] = hdf['total_bedrooms'] / hdf['total_rooms']
hdf['population_per_house_hold'] = hdf['population'] / hdf['households']

In [21]:
corr_M = hdf.corr()

In [22]:
corr_M['median_house_value']

longitude                   -0.045967
latitude                    -0.144160
housing_median_age           0.105623
total_rooms                  0.134153
total_bedrooms               0.049686
population                  -0.024650
households                   0.065843
median_income                0.688075
median_house_value           1.000000
rooms_per_house              0.151948
bebrooms_per_room           -0.255880
population_per_house_hold   -0.023737
Name: median_house_value, dtype: float64

Обработка пустых значений

In [21]:
#hdf.dropna(subset = ['total_bedrooms'])

In [30]:
hdf.drop(['total_bedrooms'], axis = 1)


longitude  latitude  housing_median_age  total_rooms  population  \
0        -122.23     37.88                41.0        880.0       322.0   
1        -122.22     37.86                21.0       7099.0      2401.0   
2        -122.24     37.85                52.0       1467.0       496.0   
3        -122.25     37.85                52.0       1274.0       558.0   
4        -122.25     37.85                52.0       1627.0       565.0   
...          ...       ...                 ...          ...         ...   
20635    -121.09     39.48                25.0       1665.0       845.0   
20636    -121.21     39.49                18.0        697.0       356.0   
20637    -121.22     39.43                17.0       2254.0      1007.0   
20638    -121.32     39.43                18.0       1860.0       741.0   
20639    -121.24     39.37                16.0       2785.0      1387.0   

       households  median_income  median_house_value ocean_proximity  \
0           126.0         8.3252            452600.0        NEAR BAY   
1          1138.0         8.3014            358500.0        NEAR BAY   
2           177.0         7.2574            352100.0        NEAR BAY   
3           219.0         5.6431            341300.0        NEAR BAY   
4           259.0         3.8462            342200.0        NEAR BAY   
...           ...            ...                 ...             ...   
20635       330.0         1.5603             78100.0          INLAND   
20636       114.0         2.5568             77100.0          INLAND   
20637       433.0         1.7000             92300.0          INLAND   
20638       349.0         1.8672             84700.0          INLAND   
20639       530.0         2.3886             89400.0          INLAND   

       rooms_per_house  bebrooms_per_room  population_per_house_hold  
0             6.984127           0.146591                   2.555556  
1             6.238137           0.155797                   2.109842  
2             8.288136           0.129516                   2.802260  
3             5.817352           0.184458                   2.547945  
4             6.281853           0.172096                   2.181467  
...                ...                ...                        ...  
20635         5.045455           0.224625                   2.560606  
20636         6.114035           0.215208                   3.122807  
20637         5.205543           0.215173                   2.325635  
20638         5.329513           0.219892                   2.123209  
20639         5.254717           0.221185                   2.616981  

[20640 rows x 12 columns]

In [13]:
#mediantb = hdf['total_bedrooms'].median()
#hdf['total_bedrooms'].fillna(mediantb, inplace = True)

#medianpbr = hdf['bebrooms_per_room'].median()
#hdf['bebrooms_per_room'].fillna(medianpbr, inplace = True)


In [ ]:
# Отделение меток

In [31]:
X = hdf.drop(['median_house_value'], axis = 1)

In [32]:
Y = hdf['median_house_value']

In [33]:
#X

In [34]:
#Y

Обработка категориальных признаков

In [35]:
h_cat_en, h_categories = X['ocean_proximity'].factorize()

In [36]:
#h_cat_en

In [37]:
#h_categories

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [39]:
oh = OneHotEncoder()

In [40]:
coded = oh.fit_transform(h_cat_en.reshape(-1,1))

In [41]:
#coded

In [42]:
#coded.toarray()

In [43]:
proxy = pd.DataFrame(coded.toarray(), index = X.index, columns = ['1','2','3','4','5'])

In [44]:
#X

In [45]:
X = pd.concat([X, proxy], axis = 1)

In [46]:
#X

In [47]:
X = X.drop(['ocean_proximity'], axis = 1)

In [48]:
# масштабирование и стандартизация значений

In [49]:
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
X = mms.fit_transform(X)

In [50]:
from sklearn.preprocessing import StandardScaler
mms = StandardScaler()
X = mms.fit_transform(X)

In [51]:
#X

Создание проверочного набора

In [52]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train,  Y_test =  train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [53]:
X_train.shape, Y_train.shape

((16512, 16), (16512,))

READY to ROCK

In [54]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()

In [55]:
linreg.fit(X_train, Y_train)

LinearRegression()

In [56]:
someData = X_train[:6]
someLabels = Y_train[:6]

In [57]:
# прогноз
preds = linreg.predict(someData)

In [58]:
# Оценка на обучающем множестве

In [59]:
preds

array([181666.10584726, 290474.10584726, 244840.10584726, 146422.10584726,
       163223.18592539, 316809.18592539])

In [60]:
someLabels

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
17848    264800.0
Name: median_house_value, dtype: float64

In [61]:
from sklearn.metrics import mean_squared_error
import math
mse = mean_squared_error(preds, someLabels)
rmse = math.sqrt(mse)
rmse

70439.78072370133

Дерево решений

In [62]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor()

In [63]:
tree.fit(X_train, Y_train)

DecisionTreeRegressor()

In [64]:
preds = tree.predict (someData)

In [65]:
preds

array([103000., 382100., 172600.,  93400.,  96500., 264800.])

In [66]:
someLabels

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
17848    264800.0
Name: median_house_value, dtype: float64

In [67]:
from sklearn.metrics import mean_squared_error
import math
mse = mean_squared_error(preds, someLabels)
rmse = math.sqrt(mse)
rmse

0.0

Случайный лес

In [68]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor()

In [69]:
forest.fit(X_train, Y_train)

RandomForestRegressor()

In [70]:
preds = forest.predict (someData)

In [71]:
preds

array([107705.  , 382711.05, 188812.  ,  91548.  ,  96407.  , 280530.01])

In [72]:
someLabels

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
17848    264800.0
Name: median_house_value, dtype: float64

In [73]:
from sklearn.metrics import mean_squared_error
import math
mse = mean_squared_error(preds, someLabels)
rmse = math.sqrt(mse)
rmse

9453.492464891835

GRID SEARCH

In [74]:
from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [3,10,30], 'max_features':[2,4,6,8]}

forest_reg = forest = RandomForestRegressor()

grid_search = GridSearchCV(forest_reg, param_grid, cv = 5, scoring = 'neg_mean_squared_error')

In [75]:
grid_search.fit(X_train, Y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(),
             param_grid={'max_features': [2, 4, 6, 8],
                         'n_estimators': [3, 10, 30]},
             scoring='neg_mean_squared_error')

In [76]:
grid_search.best_params_

{'max_features': 6, 'n_estimators': 30}

In [77]:
grid_forest = grid_search.best_estimator_

In [78]:
preds = grid_forest.predict(someData)

In [79]:
preds

array([108893.33333333, 370466.66666667, 196896.66666667,  95886.66666667,
       102770.        , 276253.36666667])

In [80]:
someLabels

14196    103000.0
8267     382100.0
17445    172600.0
14265     93400.0
2271      96500.0
17848    264800.0
Name: median_house_value, dtype: float64

In [81]:
from sklearn.metrics import mean_squared_error
import math
mse = mean_squared_error(preds, someLabels)
rmse = math.sqrt(mse)
rmse

12497.132020624798

In [ ]:
# изменить метод обработки пустых значений, как изменятся оценки(я удалила total bedrooms)
# при линейной регрессии результат:rmse =  70439.78072370133
# при дереве решений : rmse =  0
# при случайном лесе :rmse = 9453.492464891835
# при GRID SEARCH : rmse = 12497.132020624798
#

Оценка на проверочном множестве

In [48]:
# линейная регрессия
Linpreds = linreg.predict(X_test)
mse = mean_squared_error(Linpreds, Y_test)
rmse = math.sqrt(mse)
rmse

69126.81294720496

In [1]:
# Дерево решений


In [2]:
# Случайный лес


In [3]:
# Случайный лес + подгон гиперпараметров


ДЗ 
1. Допишите в блоках сверху оценки на проверочном наборе для моделей: Дерево решений, Случайный лес, 
    Случайный лес после поиска гиперпараметров, по аналогии с оценками линейной модели.
2. Попробуйте не добавлять новые признаки в набор данных - как изменятся оценки?
3. Попробуйте изменить метод обработки пустых значений - как изменятся оценки?
4. Попробуйте не применять масштабирование / нормирование данных - сработают ли модели?
 